version: '3'
services:
  web: &WEB
    build: .
    command: yarn start
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    links:
      - redis
  redis:
    image: redis:5.0.3-alpine
    ports:
      - '6379:6379'

volumes:
  node_modules: {}
